/**
 * OOSE Project - Group 4 
 * Search.java
 */
package edu.jhu.twacker.vo;

import java.sql.Time;
import java.sql.Date;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Class to hold the representation of
 * a query object added to database submitted a user 
 * @author Disa Mhembere
 *
 */
@Entity
public class Search
{
	@Id
	@GeneratedValue
	private int id;
	@Basic
	private String value;
	
	public Date getDate()
	{
		return date;
	}

	//@Temporal(TemporalType.DATE)
	@Basic
	private Date date;
	
	@Basic
	private Time time;	
	
	//@Id int id;
	//@Transient User currentUser;
	
	/**
	 *  Get string containing value of a query 
	 * @return The value string
	 */
	public String getValue()
	{
		return value;
	}

	/**
	 * Set the value of a query
	 * This done via <code>jsp</code> form submission 
	 * @param value
	 */
	public void setValue(String value)
	{
		this.value = value;
	}

	/**
	 * Currently the transactional auto-generated ID. Primary key
	 * @return the id
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Set autogenerated ID. Done by persistence
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * @return the time
	 */
	public Time getTime()
	{
		return time;
	}

	/**
	 * @param time the time to set
	 */
	public void setTime(Time time)
	{
		this.time = time;
	}

	/**
	 * @param date the date to set
	 */
	public void setDate(Date date)
	{
		this.date = date;
	}
		
}
